function convertToAbbreviation(text) {
    const conversions = {
        'antigua and barbuda': 'ATG',
        'bosnia and herzegovina': 'BIH',
        'burkina faso': 'BFA',
        'central african republic': 'CAFR',
        'côte d\'ivoire': 'CIV',
        'cabo verde': 'CPV',
        'costa rica': 'CR',
        'czech republic': 'CZ',
        'democratic republic of the congo': 'DRC',
        'dominican republic': 'DOM',
        'el salvador': 'SV',
        'equatorial guinea': 'GNQ',
        'holy see': 'VAT',
        'marshall islands': 'MHL',
        'new zealand': 'NZ',
        'north macedonia': 'MKD',
        'papua new guinea': 'PNG',
        'saint kitts and nevis': 'KNA',
        'saint lucia': 'LC',
        'saint vincent and the grenadines': 'VCT',
        'san marino': 'SMR',
        'sao tome and principe': 'STP',
        'saudi arabia': 'SAU',
        'sierra leone': 'SLE',
        'solomon islands': 'SLB',
        'south africa': 'ZAF',
        'south sudan': 'SSD',
        'sri lanka': 'LKA',
        'trinidad and tobago': 'TT',
        'united arab emirates': 'UAE',
        'united kingdom': 'UK',
        'united states of america': 'USA',
        'united states': 'USA',
        'andorra la vella': 'AndorraLaVella',
        'saint john\'s': 'SaintJohns',
        'buenos aires': 'BuenosAires',
        'bandar seri begawan': 'BandarSeriBegawan',
        'phnom penh': 'PhnomPenh',
        'san josé': 'SanJosé',
        'santo domingo': 'SantoDomingo',
        'san salvador': 'SanSalvador',
        'addis ababa': 'AddisAbaba',
        'st. george\'s': 'StGeorges',
        'guatemala city': 'GuatemalaCity',
        'vatican city': 'VaticanCity',
        'new delhi': 'NewDelhi',
        'kuwait city': 'KuwaitCity',
        'luxembourg city': 'LuxembourgCity',
        'kuala lumpur': 'KualaLumpur',
        'port louis': 'PortLouis',
        'mexico city': 'MexicoCity',
        'panama city': 'PanamaCity',
        'port moresby': 'PortMoresby',
        'sao tome': 'SaoTome',
        'port of spain': 'PortOfSpain',
        'abu dhabi': 'AbuDhabi',
        'washington, d.c.': 'WashingtonDC',
        'port vila': 'PortVila',
        'el aaiún': 'ElAaiún',
        'new hampsire': 'NH',
        'new jersey': 'NJ',
        'new mexico': 'NM',
        'new york': 'NY',
        'north carolina': 'NC',
        'north dakota': 'ND',
        'rhode island': 'RI',
        'south carolina': 'SC',
        'south dakota': 'SD',
        'west virginia': 'WV',
        'meter per second': 'm/s',
        'meters per second': 'm/s',
        'kilometer per hour': 'km/h',
        'kilometers per hour': 'km/h',
        'mile per hour': 'mph',
        'miles per hour': 'mph',
        'foot per second': 'ft/s',
        'feet per second': 'ft/s',
        'square meters': 'm²',
        'square meter': 'm²',
        'square kilometers': 'km²',
        'square kilometer': 'km²',
        'square centimeters': 'cm²',
        'square centimeter': 'cm²',
        'square millimeters': 'mm²',
        'square millimeter': 'mm²',
        'square micrometers': 'µm²',
        'square micrometer': 'µm²',
        'square nanometers': 'nm²',
        'square nanometer': 'nm²',
        'square miles': 'mi²',
        'square mile': 'mi²',
        'square yards': 'yd²',
        'square yard': 'yd²',
        'square foot': 'ft²',
        'square feet': 'ft²',
        'square inches': 'in²',
        'square inch': 'in²',
        'cubic meters': 'm³',
        'cubic meter': 'm³',
        'cubic kilometers': 'km³',
        'cubic kilometer': 'km³',
        'cubic centimeters': 'cm³',
        'cubic centimeter': 'cm³',
        'cubic milimeters': 'mm³',
        'cubic millimeter': 'mm³',
        'cubic micrometers': 'µm³',
        'cubic micrometer': 'µm³',
        'cubic nanometers': 'nm³',
        'cubic nanometer': 'nm³',
        'cubic miles': 'mi³',
        'cubic mile': 'mi³',
        'cubic yards': 'yd³',
        'cubic yard': 'yd³',
        'cubic foot': 'ft³',
        'cubic feet': 'ft³',
        'cubic inches': 'in³',
        'cubic inch': 'in³',
        'fluid ounces': 'fl-oz',
        'fluid ounce': 'fl-oz',
        'fl oz': 'fl-oz',
        'north america': 'NorthAmerica',
        'south america': 'SouthAmerica',
        'Land Rover': 'LandRover',
        'Aston Martin': 'AstonMartin',
        'Alfa Romeo': 'AlfaRomeo',
        'Great Wall': 'GreatWall',
        'Louis Vuitton': 'LouisVuitton',
        'Forever 21': 'Forever21',
        'Calvin Klein': 'CalvinKlein',
        'Tommy Hilfiger': 'TommyHilfiger',
        'Ralph Lauren': 'RalphLauren',
        'Yves Saint Laurent': 'YvesSaintLaurent',
        'Under Armour': 'UnderArmour',
        'Abercrombie & Fitch': 'Abercrombie&Fitch',
        'The North Face': 'TheNorthFace',
        'Adidas Originals': 'AdidasOriginals',
        'Alexander McQueen': 'AlexanderMcQueen',
        'Michael Kors': 'MichaelKors',
        'Polo Ralph Lauren': 'PoloRalphLauren',
        'Hugo Boss': 'HugoBoss',
        'Dolce & Gabbana': 'Dolce&Gabbana',
        'Miu Miu': 'MiuMiu',
        'Visual Basic': 'VisualBasic',
        'Red deer': 'RedDeer',
        'Red deers': 'RedDeers',
        'Red panda': 'RedPanda',
        'Red pandas': 'RedPandas',
        'Sand dollar': 'SandDollar',
        'Sand dollars': 'SandDollars',
    };

    // Creamos una expresión regular que coincida con cualquiera de los nombres a abreviar
    const abbreviateRegex = new RegExp(Object.keys(conversions).join('|'), 'gi');

    // Reemplazamos los nombres en el texto con sus abreviaciones
    return text.replace(abbreviateRegex, function (match) {
        // Convierte la coincidencia a minúsculas para que coincida
        return conversions[match.toLowerCase()] || match;
    });
}